### PR TITLE
Fix uint overflow in proto_trace_tokenizer

### LINKED ISSUE #2264: Unsigned integer overflow in ProtoTraceTokenizer
In the ProtoTraceTokenizer, at https://github.com/google/perfetto/blob/edd70a17a1fdc811de00869e4e6aa6cbef92b58f/src/trace_processor/importers/proto/proto_trace_tokenizer.h#L168 there is a potential overflow in `hdr_size + field_size`. This might cause the subsequent code to read more data out of the reader than what is available.

### PR DESCRIPTION
**Pull request by antosart**
Fixes #2264.

### CODE REVIEW

File: src/trace_processor/importers/proto/proto_trace_tokenizer.h [hunk 1]
```diff
@@ -164,8 +164,9 @@ class ProtoTraceTokenizer {
       }
 
       // If there's not enough bytes in the reader, then we cannot do anymore.
-      size_t size_incl_header = hdr_size + field_size;
-      if (size_incl_header > avail) {
+      uint64_t size_incl_header = hdr_size + field_size;
```
Comment (LalitMaganti) [inline src/trace_processor/importers/proto/proto_trace_tokenizer.h]: Instead of this, I suggest writing the code as follows to avoid the overflow entriely:
```
      // If there's not enough bytes in the reader, then we cannot do anymore.
      if (field_size > avail - hdr_size) {
        return base::OkStatus();
      }
      size_t size_incl_header = hdr_size + field_size;
```

Comment (antosart) [reply src/trace_processor/importers/proto/proto_trace_tokenizer.h]: makes sense, thanks!

**Review by LalitMaganti — APPROVED** [review]
